### PR TITLE
Route and Journey pattern clashes between tnds zones

### PR DESCRIPTION
**Pull request by abrahammartin**
Add tnds_zone as a prefix to the route and journey patterns objects ids to avoid clashes between zones with the same ids for routes and journey patterns

### CODE REVIEW

**Comment by abrahammartin** [comment]
It's deployed in tfc-app3 and didn't gave me any problems. Can you test it with tfc-app4? If it works for you as well I'll then push it to 1. Thanks.

**Comment by jw35** [comment]
Will do, but not this week because I’m away on leave and only have my phone with me. Even I am not going to deploy something from a phone.

Jon

--
Jon Warbrick

On 22 Oct 2018, at 08:57, Abraham Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


It's deployed in tfc-app3 and didn't gave me any problems. Can you test it with tfc-app4? If it works for you as well I'll then push it to 1. Thanks.

**Comment by abrahammartin** [comment]
No worries! I didn't know you were on hols. Enjoy!

**Comment by jw35** [comment]
up - looks good on tfc-app4. Ran ok, and is now rendering a universal timetable that seems to match the one [here](http://www.travelineeastanglia.org.uk/ea/XSLT_TTB_REQUEST?language=en&command=direct&net=ea&line=2000U&sup=%20&itdLPxx_direction=H&project=y08&outputFormat=0&itdLPxx_displayHeader=false&itdLPxx_sessionID=EFA02_26894026&lineVer=1&itdLPxx_spTr=1&itdLPxx_operatorCodeForTTB=WHIP).

**Pull request merged**
