### PR TITLE
Lorawan connections

### PR DESCRIPTION
**Pull request by jw35**
This currently a draft to track some on-going work. 

AMC wrote:

> This is now deployed in tfc-app3 but I don't have any lorawan sensor to test the whole flow, so this is been done mostly "blind".
>
>Changes:
>
> - LoRaWAN Applications have been deleted from the website as the term doesn't mean anything in the new Everynet portal.
> - LoRaWAN Applications have been replaced by a APP_EUI new field when inserting a new sensor.
> - A new Connection model has been created. This is two thing:
>   + This is our internal representation of an Everynet HTTP Connection and the web form has the same fields.
>   + As the Everynet Connection API doesn't have a POST endpoint a manual creation of this is required. For this reason, every time someone creates a new Connection we receive an email with the parameters of the new Connection that we'll need to add manually via the UI in the Everynet web panel.
>  + Once this has been done the email provides with a link to confirm that it has been done and to enter the id of the Everynet Connection that has been created in the Everynet portal. This is important to enter as it is later used in the deletion email.
>  + As all Everynet HTTP Connection require an Everynet Filter, one is created but this time this is created via the API as Everynet Filter API allow POST messages. The Everynet Filter id is passed in the email admins receive to create a new connection as this is necessary for them to add to the Connection.
>  + Once the Connection has been confirmed in smartcambrige.org, the user receives an email informing them about it.
>- Everynet HTTP Connection objects require an Everynet Filter and this is created and updated via API, so o manual interaction is needed for that.
>- Users can associate Devices to Connections. What this does internally is add or remove them from the Everynet Filter which is the connection between Everynet HTTP Connections and Everynet Devices. Everynet Filters can filter by Device EUI, Application EUI, and others. In our case I have configured them to filter by DevEUI. This is what the end user manages in the smarcambridge website when associating devices to connections.
> - All references to tfcserver db have been deleted
> - All references to tfcserver API have been deleted
> - Django will send us from now on Django Error messages via email. These have been logged into the logs until now but I think as this should be rare is better to get them via email to warn us of a serious error (should only been sent if it is an ERROR level log).

### CODE REVIEW

**Comment by jw35** [comment]
Missing space on New Connection screen:

image

**Comment by jw35** [comment]
Weird word wrap on warning message (in a deliberately narrow browser window to emphasise problem):

image

**Comment by jw35** [comment]
Connection creation request message: 

1) Would be easier if the data was in the same order as the fields on the Everynet portal
2) Everynet don't seem to want/need 'name'
3) The Everynet connection types offered are labeled 'my Devices', 'MQTT', 'Core API' and 'HTTP v2'. Which do you mean by 'everynet_lw_http'? I'm guessing HTTP.

Device screen:

Missing 'Activation type' data:

image

**Comment by jw35** [comment]
* Would be good if the confirmation link in the 'New Connection Request' email was clickable.

* The Everynet console seems to support deep links to devices/filters/connections. It might be handy for us when debugging to have access to a page that included relavent links for CSN devices and CSN connections.

**Comment by abrahammartin** [comment]
> 1. Would be easier if the data was in the same order as the fields on the Everynet portal

This is now done, although taking into account that this is just an UI and that it can change as we don't have any control on it and is a manual process, I wouldn't rely on it too much.

> 2. Everynet don't seem to want/need 'name'

We ask for name and description (optional) in CSN, so users can find organise their connections by name. I pass this in the email for context but I'm not sure if we should be filling Everynet's description field with this content. Anyway, I have put name and description now in the same field (as description is optional) so anyone can choose to populate that or not with the info available.

> 3. The Everynet connection types offered are labeled 'my Devices', 'MQTT', 'Core API' and 'HTTP v2'. Which do you mean by 'everynet_lw_http'? I'm guessing HTTP.

Changed that now.

> Missing 'Activation type' data:

fixed

> * Would be good if the confirmation link in the 'New Connection Request' email was clickable.

It is now, but only in production as in the way it is been coded it is not possible to know from which test/dev deployment the request came from.

> * The Everynet console seems to support deep links to devices/filters/connections. It might be handy for us when debugging to have access to a page that included relavent links for CSN devices and CSN connections.

Done now in the admin console for both connections and sensors.

All in https://github.com/SmartCambridge/tfc_web/pull/292/commits/d7a8b451ac04f230af26d0130e16319b33cdffbd

**Comment by abrahammartin** [comment]
Closed in favour of #296 as I can't see any way of changing a draft PR to a normal PR.

**Pull request closed without merging**
