### PR TITLE
Add the 'Download API'

### PR DESCRIPTION
**Pull request by jw35**
The 'Download API' is a framework that provides efficient download
access to potentially large amounts of archived SmartCambridge data as
compressed CSV files. It compliments the Django REST framework-based
'Program API' and works by pre-building zipped CSV files containing
extracts of the available data for various date ranges and serving them
direct from Nginx.

See [downoad_api.md](https://github.com/SmartCambridge/tfc_web/blob/jw35-download-api/download_api.md) for details

### CODE REVIEW

**Comment by jw35** [comment]
Deployment instructions:

1. Checkout appropriate tfc_web branch in `~tfc_prod/tfc_web`; run redeploy.sh

**Comment by abrahammartin** [comment]
Screenshot 2019-11-26 at 19 04 51

lol

**Comment by abrahammartin** [comment]
is there any file in commit bbafa394f220666c90cd0d3bbb54e01a83f4331f that is not a json sample? (just to avoid going through the whole lot)

**Comment by jw35** [comment]
All Jason. Just bus position data. Just one hour!

Jon

--
Jon Warbrick

On 26 Nov 2019, at 19:40, Abraham Martin <notifications@github.com> wrote:

﻿

is there any file in commit bbafa39<https://github.com/SmartCambridge/tfc_web/commit/bbafa394f220666c90cd0d3bbb54e01a83f4331f> that is not a json sample? (just to avoid going through the whole lot)

**Pull request merged**
