### PR TITLE
Add graphs of Pocket SmartPanel usage

### PR DESCRIPTION
**Pull request by jw35**
Add new pages /smartpanel/pocketlog/unique and
/smartpanel/pocketlog/total showing graphs of 'unique clients
per week' and 'total clients ever' for the Pocket Smartpanel
(even if 'total clients' is an unhelpful metric)

The graph is drawn with D3 and uses CSV data from
/smartpanel/pocketlog/pocketlog.csv which is managed by tfc_prod.

To support this work, this edit adds copies of moment.js and
v5 of d3.js to the main tfc_web static directory.

### CODE REVIEW

**Comment by jw35** [comment]
Examples of the graphs, using real data copied from tfc-app4 can beseen at 

* https://tfc-app1.cl.cam.ac.uk/smartpanel/pocketlog/unique
* https://tfc-app1.cl.cam.ac.uk/smartpanel/pocketlog/total

**Comment by abrahammartin** [comment]
Two comments only:
 - Graphs overflow to the right:
Screenshot 2019-10-06 at 15 51 16
Screenshot 2019-10-06 at 15 51 37
 - I think adding a js event when the windows is resize to call the draw function so that the graph is redrawn is a quick easy win to make it responsive.

**Comment by jw35** [comment]
In my defence I observe that all our other graphs have the same *feature*. I'll see if I can work out what's going on.

**Comment by jw35** [comment]
> Two comments only:
> 
> * Graphs overflow to the right:

Fixed.

> - I think adding a js event when the windows is resize to call the draw function so that the graph is redrawn is a quick easy win to make it responsive.

Done.

Both changes on tfc-app1

**Pull request merged**
